### ISSUE TITLE
Suggestion: 

### ISSUE THREAD

**Issue by SladeHazard** [Enzias/EasyDuels#4]
Add multi arena support meaning if 2 players are 1v1ing  and 2 other players want to do it will teleport them to a available arena
don't care that the plugin wasn't meant for this it wouldn't hurt anyone people who don't want this can stick with 1 arena or else this plugin is useless with servers that have 50-100 players and queue system will just take forever.... 5min match

**Comment by Enzias** [comment]
Hey, thank you for this suggestion. For the moment the plugin will remain exclusively compatible with only one arena. This allows me to create more easily and faster useful features. I will probably add Multi arenas support in version 2.0 because it will need a lot of code rewrite. 
Nevertheless, if you have a suggestion that could be directly compatible with the one arena system do not hesitate, I will do my best to add it to the plugin.

Have a good night!
